# Generated by Django 3.1.7 on 2021-06-04 12:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='box_office_best_tw',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=20)),
                ('box_office', models.CharField(max_length=20)),
                ('year', models.CharField(max_length=20)),
                ('area', models.CharField(max_length=10)),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
