# Generated by Django 3.1.7 on 2021-06-05 02:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_year_champion'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='year_champion',
            new_name='anime_chapion',
        ),
    ]
