# Generated by Django 3.1.7 on 2021-06-05 03:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_auto_20210605_1055'),
    ]

    operations = [
        migrations.CreateModel(
            name='Box_office_anime_champion_year',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=20)),
                ('box_office', models.CharField(max_length=20)),
                ('area', models.CharField(max_length=10)),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Box_office_champion_year',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=20)),
                ('box_office', models.CharField(max_length=20)),
                ('area', models.CharField(max_length=10)),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
