# Generated by Django 3.1.7 on 2021-06-05 06:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_box_office_opening_first_week_box_office_opening_first_week_anime_box_office_opening_first_week_loca'),
    ]

    operations = [
        migrations.CreateModel(
            name='First_day_box_office',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=20)),
                ('box_office', models.CharField(max_length=20)),
                ('weeks', models.CharField(max_length=10)),
                ('year', models.CharField(max_length=20)),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='First_day_box_office_local',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=20)),
                ('box_office', models.CharField(max_length=20)),
                ('weeks', models.CharField(max_length=10)),
                ('year', models.CharField(max_length=20)),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Single_day_box_office',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=20)),
                ('box_office', models.CharField(max_length=20)),
                ('weeks', models.CharField(max_length=10)),
                ('year', models.CharField(max_length=20)),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
