# Generated by Django 3.1.7 on 2021-06-05 07:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0007_documentary_local_indea_movies_japan_movies_korea_movies_musical_movies_local_rank_local_scary_movie'),
    ]

    operations = [
        migrations.CreateModel(
            name='Box_office_champion_year_local',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=20)),
                ('box_office', models.CharField(max_length=20)),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
