# Generated by Django 3.2.3 on 2021-06-13 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0013_tawain_movies_rank_2019'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tawain_movies_rank_2017',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.CharField(max_length=10)),
                ('area', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=20)),
                ('dates', models.CharField(max_length=20)),
                ('applicant', models.CharField(max_length=100)),
                ('tickets', models.CharField(max_length=20)),
                ('Total_Sale_Figure', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Tawain_movies_rank_2018',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.CharField(max_length=10)),
                ('area', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=20)),
                ('dates', models.CharField(max_length=20)),
                ('applicant', models.CharField(max_length=100)),
                ('tickets', models.CharField(max_length=20)),
                ('Total_Sale_Figure', models.CharField(max_length=20)),
            ],
        ),
    ]
