# Generated by Django 3.2.3 on 2021-06-17 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0014_tawain_movies_rank_2017_tawain_movies_rank_2018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tawain_movies_rank_2017',
            name='Total_Sale_Figure',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tawain_movies_rank_2017',
            name='tickets',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tawain_movies_rank_2018',
            name='Total_Sale_Figure',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tawain_movies_rank_2018',
            name='tickets',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tawain_movies_rank_2019',
            name='Total_Sale_Figure',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tawain_movies_rank_2019',
            name='tickets',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tawain_movies_rank_2020',
            name='Total_Sale_Figure',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tawain_movies_rank_2020',
            name='tickets',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tawain_movies_rank_2021',
            name='Total_Sale_Figure',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tawain_movies_rank_2021',
            name='tickets',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
