# Generated by Django 3.2.3 on 2021-06-17 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0015_auto_20210617_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tawain_movies_rank_2017',
            name='rank',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tawain_movies_rank_2018',
            name='rank',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tawain_movies_rank_2019',
            name='rank',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tawain_movies_rank_2020',
            name='rank',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tawain_movies_rank_2021',
            name='rank',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
