# Generated by Django 3.1.7 on 2021-06-20 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0017_auto_20210620_2108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='box_office_best_tw',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
